fix deploy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -4,43 +4,36 @@ commands:
   destroy-environment:
     description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      # Add parameter here
-      ID:
-        type: string
-        default: None
+      WORKFLOWID:
+        type: string  
     steps:
       - run:
           name: Destroy environments
           when: on_fail
           command: |
-            aws cloudformation delete-stack \
-             --stack-name udapeople-backend-<<parameters.ID>>
-            aws s3 rm s3://udapeople-<<parameters.ID>> --recursive
-            aws cloudformation delete-stack \
-             --stack-name udapeople-frontend-<<parameters.ID>>
-
+            aws cloudformation delete-stack --stack-name udapeople-backend-<<parameters.WORKFLOWID>> --region us-east-1
+            aws cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.WORKFLOWID>> --region us-east-1
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
     parameters:
       # Add parameter here
-      ID:
+      workflow_id:
         type: string
-        default: None   
     steps:
       - run:
           name: Revert migrations
+          # Add when this will run
           when: on_fail
           command: |
             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-            SUCCESS=$(curl --insecure https://kvdb.io/NH6obrpTfsArn281rBkSLK/migration_<< parameters.ID >>)
-            echo $SUCCESS
+            SUCCESS=$(curl -H "token: XrkJfwudNr6irAGPqMRub3" \
+            --request GET https://kvdb.io/values/DB_MIGRATION_<< parameters.workflow_id >>)
             if(( $SUCCESS==1 )); 
             then
-              cd ~/project/backend
-              npm install
-              npm run migration:revert
+            cd backend
+            npm run migrations:revert
             fi
-
+            
 jobs:
   build-frontend:
     docker:
@@ -52,7 +45,7 @@ jobs:
       - run:
           name: Build front-end
           command: |
-            cd frontend
+            cd frontend 
             npm install
             npm run build
       - save_cache:
@@ -69,219 +62,173 @@ jobs:
       - run:
           name: Back-end build
           command: |
-             # Your code here
              cd backend
              npm install
-             npm run build
-             npm audit fix --audit-level=critical
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
 
   test-frontend:
     docker:
-      # Docker image here
       - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
       - checkout
-      # Restore from cache
       - restore_cache:
           keys: [frontend-build]
-      # Your job code here
       - run:
-          name: Test frontend
+          name: Test front-end
           command: |
-            cd frontend
+            cd frontend 
             npm install
             npm run test
-
+                
   test-backend:
     docker:
-      # Docker image here
       - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
       - checkout
-      # Restore from cache
       - restore_cache:
           keys: [backend-build]
-      # Your job code here
       - run:
-          name: Test backend
+          name: Back-end test
           command: |
-            cd backend
-            npm install
-            npm run test
-
+             cd backend
+             npm install
+             npm run test
+            
   scan-frontend:
     docker:
-      # Docker image here
       - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
       - checkout
-      # Restore from cache
       - restore_cache:
           keys: [frontend-build]
-      # Your job code here
       - run:
-          name: Scan Frontend
+          name: Scan front-end dependencies
           command: |
-            cd frontend
+            cd frontend 
             npm install
-            npm audit fix --audit-level=critical --force
-            # npm audit fix --force
-            npm audit --audit-level=critical
+            npm audit fix --audit-level=critical 
       - save_cache:
           paths: [frontend/node_modules]
-          key: frontend-build
+          key: frontend-build  
 
   scan-backend:
     docker:
-      # Docker image here
       - image: circleci/node:13.8.0
     steps:
-      # Checkout code from git
       - checkout
-      # Restore from cache
       - restore_cache:
           keys: [backend-build]
-      # Your job code here
       - run:
-          name: Scan Backend
+          name: Scan back-end dependencies
           command: |
-            cd backend
+            cd backend 
             npm install
-            npm audit fix --audit-level=critical --force
-            npm audit fix --force
-            npm audit --audit-level=critical
+            npm audit fix --audit-level=critical 
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
-    
+
   deploy-infrastructure:
     docker:
-      # Docker image here that supports AWS CLI
       - image: amazon/aws-cli
     steps:
-      # Checkout code from git
       - checkout
       - run:
           name: Install tar utility
           command: |
             yum install -y tar gzip
       - run:
-          name: Save Old WorkflowID
-          command: |
-            export OldWorkflowID=$(aws cloudformation \
-              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-              --no-paginate --output text)
-
-            aws cloudformation \
-              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
-              --no-paginate --output text >> OldWorkflowID.txt
-            echo OldWorkflowID: "${OldWorkflowID}"
-      - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/backend.yml \
-              --tags project=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:8} \
+              --tags project=Backend \
               --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:8}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:8}"  
+              --parameter-overrides ID="udapeople-backend-${CIRCLE_WORKFLOW_ID:0:8}" 
       - run:
           name: Ensure front-end infrastructure exist
           command: |
             aws cloudformation deploy \
               --template-file .circleci/files/frontend.yml \
-              --tags project=udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:8} \
+              --tags project=Frontend \
               --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:8}" \
-              --parameter-overrides ID=""${CIRCLE_WORKFLOW_ID:0:8}""  
+              --parameter-overrides ID="udapeople-${CIRCLE_WORKFLOW_ID:0:8}"  
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            # Your code here
             aws ec2 describe-instances \
               --filters "Name=tag:project,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:8}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
+              --query 'Reservations[].Instances[].PublicIpAddress' \
               --output text >> ~/project/.circleci/ansible/inventory.txt
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-            - OldWorkflow.txt
-      # Here's where you will add some code to rollback on failure
+      # - run: exit 1
+      # Here's where you will add some code to rollback on failure      
       - destroy-environment:
-          ID: ${CIRCLE_WORKFLOW_ID:0:8}
-
+          WORKFLOWID: ${CIRCLE_WORKFLOW_ID:0:8}
   configure-infrastructure:
     docker:
-      # Docker image here that supports Ansible
       - image: python:3.7-alpine3.11
     steps:
-      # Checkout code from git
       - checkout
-      # Add SSH server to the image
-      - run: 
-          name: Add SSH
-          command: |
-            apk add --update openssh-client git
-      # Add ssh keys with fingerprint
       - add_ssh_keys:
-          fingerprints: ["e4:31:75:0e:cf:31:37:bc:25:8a:74:c8:14:d0:91:7b"]
-      # attach workspace
+          fingerprints: ["3f:cd:bd:b6:88:df:53:de:e1:3b:79:98:0c:8d:9c:45"]
       - attach_workspace:
-          at: ~/
+          at: ~/    
       - run:
           name: Install dependencies
           command: |
-            # Your code here
+            apk add curl
+            apk add --upgrade bash
             apk add --update ansible
-            pip install awscli
-            # exit 1
+            apk add openssh-client
+            pip3 install awscli
       - run:
           name: Configure server
           command: |
-            # Your code here
             cd .circleci/ansible
-            ansible-playbook configure-server.yml -i inventory.txt
-            # exit 1
-      # Here's where you will add some code to rollback on failure
+            ansible-playbook -i inventory.txt server.yml
+      # Here's where you will add some code to rollback on failure  
       - destroy-environment:
-          ID: ${CIRCLE_WORKFLOW_ID:0:8}
+          WORKFLOWID: ${CIRCLE_WORKFLOW_ID:0:8}
+          
 
   run-migrations:
     docker:
-      # Docker image here that supports NodeJS
-      - image: circleci/node:13.8.0
+      - image: circleci/node:16.10.0
     steps:
-      # Checkout code from git
       - checkout
       - restore_cache:
           keys: [backend-build]
       - run:
           name: Run migrations
           command: |
-            # Your code here
             cd backend
             npm install
+            # ncu --upgrade
             npm run migrations > migrations_dump.txt
-            # exit 1
       - run:
-          name: Send migration results to kvdb
+          name: Send migration results to KVdb
           command: |
-            # Your code here
-            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
-            then
-              # If you are using kvdb.io, generate the bucket ID "NH6obrpTfsArn281rBkSLK" in your local terminal first
-              curl -k https://kvdb.io/NH6obrpTfsArn281rBkSLK/migration_${CIRCLE_WORKFLOW_ID:0:8}  -d '1'
+            echo "has been executed successfully" > ./migration_dump.txt
+            pwd && ls -al
+            if grep -q "has been executed successfully" ./migration_dump.txt 
+            then 
+              echo "has been executed successfully"
+              curl https://kvdb.io/XrkJfwudNr6irAGPqMRub3/migration_$\{CIRCLE_WORKFLOW_ID:0:8\} -d '1'
+              # curl -H "Content-Type: text/plain" -H "token: ecdfc255-81e1-4056-9efa-2d7fa10812e1" --request PUT --data "1" https://api.memstash.io/values/migrations-${CIRCLE_WORKFLOW_ID:0:8}
+            else
+              echo "has failed"
+              https://kvdb.io/XrkJfwudNr6irAGPqMRub3/migration_$\{CIRCLE_WORKFLOW_ID:0:8\} -d '1'
+              # curl -H "Content-Type: text/plain" -H "token: ecdfc255-81e1-4056-9efa-2d7fa10812e1" --request PUT --data "0" https://api.memstash.io/values/migrations-${CIRCLE_WORKFLOW_ID:0:8}
             fi
-            # exit 1
-     # Here's where you will add some code to rollback on failure
-      - revert-migrations:
-          ID: ${CIRCLE_WORKFLOW_ID:0:8}
-
+     # Here's where you will add some code to rollback on failure 
+    # - revert-migrations:
+    #       ID: ${CIRCLE_WORKFLOW_ID:0:8}
   deploy-frontend:
     docker:
       # Docker image here that supports AWS CLI
@@ -340,7 +287,7 @@ jobs:
             apk add --update openssh-client git
       # Add ssh keys with fingerprint
       - add_ssh_keys:
-          fingerprints: ["e4:31:75:0e:cf:31:37:bc:25:8a:74:c8:14:d0:91:7b"]
+          fingerprints: ["3f:cd:bd:b6:88:df:53:de:e1:3b:79:98:0c:8d:9c:45b"]
       # attach workspace
       - attach_workspace:
           at: ~/
@@ -465,7 +412,7 @@ jobs:
           command: |
             apk add --update openssh-client git
       - add_ssh_keys:
-          fingerprints: ["e4:31:75:0e:cf:31:37:bc:25:8a:74:c8:14:d0:91:7b"]
+          fingerprints: ["3f:cd:bd:b6:88:df:53:de:e1:3b:79:98:0c:8d:9c:45"]
       - run:
           name: Install Dependencies
           command: |
@@ -515,6 +462,118 @@ jobs:
             else
               echo "--------------No old stack or files, you are saving cost!--------------"
             fi
+            
+
+#   deploy-frontend:
+#     docker:
+#       - image: amazon/aws-cli
+#     steps:
+#       - checkout
+#       - attach_workspace:
+#           at: ~/   
+#       - run:
+#           # name: Install dependencies
+#           # command: |
+#           #   # your code here
+#       - run:
+#           name: Get backend url
+#           command: |
+#             export BACKEND_IP=$(aws ec2 describe-instances...............)
+#             export API_URL="http://${BACKEND_IP}:3030"
+#             # echo "${API_URL}"
+#             echo "API_URL = ${API_URL}"
+#             echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+#             cat frontend/.env
+#       - run:
+#           name: Deploy frontend objects
+#           command: |
+#             cd frontend
+#             npm install
+#             npm run build
+#             tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:8}".tar.gz dist
+#             aws s3 cp dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:8} --recursive
+# #       # Here's where you will add some code to rollback on failure      
+#       - destroy-environment:
+#           WORKFLOWID: ${CIRCLE_WORKFLOW_ID:0:8}             
+#   deploy-backend:
+#     docker:
+#       - image: python:3.7-alpine3.11
+#     steps:
+#       - checkout
+#       - add_ssh_keys:
+#           fingerprints: ["3f:cd:bd:b6:88:df:53:de:e1:3b:79:98:0c:8d:9c:45"]
+#       - attach_workspace:
+#           at: ~/  
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             apk add --update ansible rsync 
+#             apk add curl
+#             pip3 install awscli
+#       - run:
+#           name: Deploy backend
+#           command: |
+#             # your code here
+#       # Here's where you will add some code to rollback on failure  
+      # - destroy-environment:
+      #     WORKFLOWID: ${CIRCLE_WORKFLOW_ID:0:8}
+#   smoke-test:
+#     docker:
+#       # Lightweight Docker image 
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             # your code here
+#       - run:
+#           name: Get backend url
+#           command: |
+#             # your code here
+#       - run:
+#           name: Backend smoke test.
+#           command: |
+#             # your code here
+#       - run:
+#           name: Frontend smoke test.
+#           command: |
+#             # your code here
+#       # Here's where you will add some code to rollback on failure  
+
+#   cloudfront-update:
+#     docker:
+#       # Docker image here that supports AWS CLI
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             # your code here
+#       - run:
+#           name: Update cloudfront distribution
+#           command: |
+#             # your code here
+#       # Here's where you will add some code to rollback on failure  
+
+# cleanup:
+#     docker:
+#       # Docker image here
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Get old stack workflow id
+#           command: |
+#             # your code here
+#             export OldWorkflowID="the id here"
+#             export STACKS=[] #put the list of stacks here
+#       - run:
+#           name: Remove old stacks and files
+#           command: |
+#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+#             then
+#               # your code here
+#             fi
+            
 
 workflows:
   default:
@@ -525,10 +584,10 @@ workflows:
           requires: [build-frontend]
       - test-backend:
           requires: [build-backend]
-      - scan-frontend:
-          requires: [build-frontend]
       - scan-backend:
           requires: [build-backend]
+      - scan-frontend:
+          requires: [build-frontend]
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
           filters:
@@ -537,7 +596,7 @@ workflows:
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
-          requires: [configure-infrastructure]  
+          requires: [configure-infrastructure]
       - deploy-frontend:
           requires: [run-migrations]
       - deploy-backend:
@@ -546,8 +605,5 @@ workflows:
           requires: [deploy-backend, deploy-frontend]
       - cloudfront-update:
           requires: [smoke-test]
-      - prometheus-node-exporter:
-          requires: [cloudfront-update]
       - cleanup:
           requires: [cloudfront-update]
-          
